### ISSUE TITLE
Error on reload of any route other than index

### ISSUE THREAD

**Issue by bvellek** [bvellek/lumen-spot-app#1]
Initial server side rendering of app works at index route `/` and navigation of app within the provided links works fine. If you try to refresh the page on the `/location` route then you receive this error

```
Invariant Violation: Could not find "store" in either the context or props of "Connect(LocationContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LocationContainer)".
``` 

The app worked (and refreshed), with or without javascript enabled, from any route prior to adding redux/store.

Currently:
* On the server the entry point the app is `./public/js/components/router.js` which is rendered to a string and injected into the `pug` template.
* The client entry point is `./public/js/index.js` which uses a `Provider` from redux and a `<CLIRouter />` component.
* The store is created in `./public/js/store.js` and imported into the client entry point.

the current server setup is similar to that found in this [tutorial](https://scotch.io/tutorials/react-on-the-server-for-beginners-build-a-universal-react-and-node-app)

to run app locally `yarn build` then `yarn start` and go to `localhost:8081`

**Comment by jpdevries** [comment]
Hey Ben. I checked out the master branch and can't reproduce this. Can you provide any more specific steps to reproduce? I can refresh the `/location` page. When I do a search and hit submit though  I don't see any XHR requests made and don't notice any data update on the page.

**Comment by jpdevries** [comment]
Still haven't reproduced the issue but I noticed if you log out `renderProps` in `server.js` you get the below output which shows that `state` on the location properties is undefined. Might be a clue.

<details>
<summary>renderProps</summary>

```js
{ routes: 
   [ { path: '/',
       component: [Function: PageContainer],
       indexRoute: [Object],
       childRoutes: [Object] },
     { path: 'location', component: [Function: LocationContainer] } ],
  params: {},
  location: 
   { pathname: '/location',
     search: '',
     hash: '',
     state: undefined,
     action: 'POP',
     key: 'rq2b84',
     query: {} },
  components: [ [Function: PageContainer], [Function: LocationContainer] ],
  router: 
   { getCurrentLocation: [Function: getCurrentLocation],
     listenBefore: [Function: listenBefore],
     listen: [Function: listen],
     transitionTo: [Function: transitionTo],
     push: [Function: push],
     replace: [Function: replace],
     go: [Function: go],
     goBack: [Function: goBack],
     goForward: [Function: goForward],
     createKey: [Function: createKey],
     createPath: [Function: createPath],
     createHref: [Function: createHref],
     createLocation: [Function: createLocation],
     canGo: [Function: canGo],
     setRouteLeaveHook: [Function: listenBeforeLeavingRoute],
     isActive: [Function: isActive],
     location: 
      { pathname: '/location',
        search: '',
        hash: '',
        state: undefined,
        action: 'POP',
        key: 'rq2b84',
        query: {} },
     params: {},
     routes: [ [Object], [Object] ] },
  matchContext: 
   { transitionManager: 
      { isActive: [Function: isActive],
        match: [Function: match],
        listenBeforeLeavingRoute: [Function: listenBeforeLeavingRoute],
        listen: [Function: listen] },
     router: 
      { getCurrentLocation: [Function: getCurrentLocation],
        listenBefore: [Function: listenBefore],
        listen: [Function: listen],
        transitionTo: [Function: transitionTo],
        push: [Function: push],
        replace: [Function: replace],
        go: [Function: go],
        goBack: [Function: goBack],
        goForward: [Function: goForward],
        createKey: [Function: createKey],
        createPath: [Function: createPath],
        createHref: [Function: createHref],
        createLocation: [Function: createLocation],
        canGo: [Function: canGo],
        setRouteLeaveHook: [Function: listenBeforeLeavingRoute],
        isActive: [Function: isActive],
        location: [Object],
        params: {},
        routes: [Object] } } }

```
</details>

**Comment by bvellek** [comment]
Hey JP, 
I am not sure why your experience would be any different from mine... when I `yarn start` and go directly to `localhost:8081/location` I get the error 

```
Invariant Violation: Could not find "store" in either the context or props of "Connect(LocationContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LocationContainer)".
...
```

If i start at `localhost:8081/` I am able to navigate to `location` using either the search  link at the top or the "find your light" link midway down the landing page. I can then search for a location or use my current location to have a fetch occur and get the results. 

I noticed that the deployed version at https://lumen-spot.herokuapp.com/ has the same issue, except the error reads `Internal server error`.

I am not sure why we are getting different results. everything is up to date on the master branch and I just double checked that what I have locally is the same as on github.

**Comment by bvellek** [comment]
Added access to store on ssr and passed state to client-side. Issue Fixed
